package analise;

/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;

import java.lang.*;
import java.io.IOException;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>lexer.flex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\10\1\11\1\11\1\10\22\0\1\7\1\27\3\0"+
    "\1\34\1\25\1\0\1\40\1\41\1\2\1\32\1\37\1\33\1\36"+
    "\1\1\1\3\11\4\1\0\1\35\1\30\1\26\1\31\2\0\1\6"+
    "\21\0\1\56\6\0\1\6\1\44\1\0\1\45\1\0\1\12\1\0"+
    "\1\17\1\52\1\46\1\20\1\14\1\63\1\22\1\60\1\21\2\0"+
    "\1\13\1\57\1\54\1\23\1\50\1\0\1\16\1\47\1\15\1\51"+
    "\1\55\1\62\1\53\1\61\1\6\1\42\1\24\1\43\7\0\1\11"+
    "\u1fa2\0\1\11\1\11\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\5\1\4\7\0"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\25\0\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\14\0\1\35\10\0\1\36\4\0\1\37\11\0\1\40"+
    "\1\0\1\41\1\42\5\0\1\43\2\0\1\44\7\0"+
    "\1\45\5\0\1\46\1\47\1\0\1\50\1\0\1\51"+
    "\1\52\1\53\1\0\1\54\1\0\1\55\1\56\13\0"+
    "\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\150\0\u0104\0\u0104"+
    "\0\u0138\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\150\0\150\0\150\0\150\0\150"+
    "\0\150\0\150\0\150\0\150\0\150\0\150\0\150\0\u0374"+
    "\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478\0\u04ac\0\u04e0\0\u0514"+
    "\0\u0548\0\u057c\0\u05b0\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4"+
    "\0\u06e8\0\u071c\0\u0750\0\u0784\0\150\0\150\0\150\0\150"+
    "\0\150\0\150\0\150\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888"+
    "\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4\0\u05b0"+
    "\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94"+
    "\0\150\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\150\0\u0c98\0\u0ccc"+
    "\0\u0d00\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\150"+
    "\0\u0e6c\0\150\0\150\0\u0ea0\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70"+
    "\0\150\0\u0fa4\0\u0fd8\0\150\0\u100c\0\u1040\0\u1074\0\u10a8"+
    "\0\u10dc\0\u1110\0\u1144\0\150\0\u1178\0\u11ac\0\u11e0\0\u1214"+
    "\0\u1248\0\150\0\150\0\u127c\0\150\0\u12b0\0\150\0\150"+
    "\0\150\0\u12e4\0\150\0\u1318\0\150\0\150\0\u134c\0\u1380"+
    "\0\u13b4\0\u13e8\0\u141c\0\u1450\0\u1484\0\u14b8\0\u14ec\0\u1520"+
    "\0\u1554\0\150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\6\1\0\1\7\1\11\1\12\1\13\1\14\1\7"+
    "\1\0\1\15\2\0\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\0\1\43\1\0\1\44\1\45\1\46\1\47\2\0"+
    "\1\50\1\51\2\0\1\52\145\0\10\53\2\0\55\53"+
    "\2\5\3\53\2\0\52\53\12\0\1\7\1\54\4\0"+
    "\1\55\57\0\1\56\62\0\1\57\37\0\1\60\26\0"+
    "\1\61\41\0\1\62\17\0\1\63\123\0\1\64\6\0"+
    "\1\65\24\0\1\66\64\0\1\67\64\0\1\70\63\0"+
    "\1\71\63\0\1\72\63\0\1\73\50\0\1\74\65\0"+
    "\1\75\117\0\1\76\35\0\1\77\54\0\1\100\72\0"+
    "\1\101\55\0\1\102\43\0\1\103\21\0\1\104\124\0"+
    "\1\105\22\0\1\106\44\0\2\52\1\107\61\52\3\0"+
    "\2\110\73\0\1\111\70\0\1\112\116\0\1\113\56\0"+
    "\1\114\31\0\1\115\117\0\1\116\33\0\1\117\57\0"+
    "\1\120\63\0\1\121\65\0\1\122\63\0\1\123\116\0"+
    "\1\124\34\0\1\125\122\0\1\126\22\0\1\127\60\0"+
    "\1\130\114\0\1\131\35\0\1\132\63\0\1\133\55\0"+
    "\1\134\50\0\1\52\1\6\1\107\61\52\15\0\1\135"+
    "\70\0\1\136\63\0\1\137\55\0\1\140\63\0\1\141"+
    "\63\0\1\142\116\0\1\143\65\0\1\144\61\0\1\145"+
    "\31\0\1\146\61\0\1\147\63\0\1\150\70\0\1\151"+
    "\64\0\1\152\57\0\1\153\122\0\1\154\22\0\1\155"+
    "\117\0\1\156\32\0\1\157\66\0\1\160\57\0\1\161"+
    "\122\0\1\162\25\0\1\163\114\0\1\164\35\0\1\165"+
    "\63\0\1\166\56\0\1\167\123\0\1\170\23\0\1\171"+
    "\63\0\1\172\63\0\1\173\66\0\1\7\61\0\1\174"+
    "\126\0\1\175\23\0\1\176\117\0\1\177\55\0\1\200"+
    "\63\0\1\201\34\0\1\202\66\0\1\203\120\0\1\204"+
    "\27\0\1\7\107\0\1\205\70\0\1\206\45\0\1\207"+
    "\50\0\1\210\111\0\1\211\27\0\1\212\104\0\1\213"+
    "\75\0\1\214\31\0\1\215\66\0\1\216\116\0\1\217"+
    "\24\0\1\220\61\0\1\221\124\0\1\222\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5512];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\11\2\1\1\11\2\1\7\0\4\1"+
    "\14\11\25\0\7\11\14\0\1\1\10\0\1\11\4\0"+
    "\1\11\11\0\1\11\1\0\2\11\5\0\1\11\2\0"+
    "\1\11\7\0\1\11\5\0\2\11\1\0\1\11\1\0"+
    "\3\11\1\0\1\11\1\0\2\11\13\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[146];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is) {
		this(is);
        symbolFactory = sf;
    }
    
    public Lexer(java.io.InputStream in) {
        this(new java.io.InputStreamReader(in));
      }
    
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1), // -yylength()
						new Location(yyline+1,yycolumn+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
	return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1), 
						new Location(yyline+1,yycolumn+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    	System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    	System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 180) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return symbolFactory.newSymbol("A_DIV",A_DIV);
            }
          case 48: break;
          case 2: 
            { return symbolFactory.newSymbol("A_MULT",A_MULT);
            }
          case 49: break;
          case 3: 
            { return symbolFactory.newSymbol("INTEIRO",INTEIRO,yytext());
            }
          case 50: break;
          case 4: 
            { 
            }
          case 51: break;
          case 5: 
            { return symbolFactory.newSymbol("IDENTIFICADOR",IDENTIFICADOR,yytext());
            }
          case 52: break;
          case 6: 
            { return symbolFactory.newSymbol("IGUAL",IGUAL);
            }
          case 53: break;
          case 7: 
            { return symbolFactory.newSymbol("OP_NOT",OP_NOT);
            }
          case 54: break;
          case 8: 
            { return symbolFactory.newSymbol("OP_LT",OP_LT);
            }
          case 55: break;
          case 9: 
            { return symbolFactory.newSymbol("OP_GT",OP_GT);
            }
          case 56: break;
          case 10: 
            { return symbolFactory.newSymbol("A_PLUS",A_PLUS);
            }
          case 57: break;
          case 11: 
            { return symbolFactory.newSymbol("A_MINUS",A_MINUS);
            }
          case 58: break;
          case 12: 
            { return symbolFactory.newSymbol("A_MOD",A_MOD);
            }
          case 59: break;
          case 13: 
            { return symbolFactory.newSymbol("PONTOVIRGULA",PONTOVIRGULA);
            }
          case 60: break;
          case 14: 
            { return symbolFactory.newSymbol("PONTO",PONTO);
            }
          case 61: break;
          case 15: 
            { return symbolFactory.newSymbol("VIRGULA",VIRGULA);
            }
          case 62: break;
          case 16: 
            { return symbolFactory.newSymbol("PARENT_ESQ",PARENT_ESQ);
            }
          case 63: break;
          case 17: 
            { return symbolFactory.newSymbol("PARENT_DIR",PARENT_DIR);
            }
          case 64: break;
          case 18: 
            { return symbolFactory.newSymbol("CURLY_ESQ",CURLY_ESQ);
            }
          case 65: break;
          case 19: 
            { return symbolFactory.newSymbol("CURLY_DIR",CURLY_DIR);
            }
          case 66: break;
          case 20: 
            { return symbolFactory.newSymbol("COLCHE_ESQ",COLCHE_ESQ);
            }
          case 67: break;
          case 21: 
            { return symbolFactory.newSymbol("COLCHE_DIR",COLCHE_DIR);
            }
          case 68: break;
          case 22: 
            { return symbolFactory.newSymbol("K_IF",K_IF);
            }
          case 69: break;
          case 23: 
            { return symbolFactory.newSymbol("OP_OR",OP_OR);
            }
          case 70: break;
          case 24: 
            { return symbolFactory.newSymbol("OP_AND",OP_AND);
            }
          case 71: break;
          case 25: 
            { return symbolFactory.newSymbol("OP_EQ",OP_EQ);
            }
          case 72: break;
          case 26: 
            { return symbolFactory.newSymbol("OP_DIF",OP_DIF);
            }
          case 73: break;
          case 27: 
            { return symbolFactory.newSymbol("OP_LET",OP_LET);
            }
          case 74: break;
          case 28: 
            { return symbolFactory.newSymbol("OP_GET",OP_GET);
            }
          case 75: break;
          case 29: 
            { return symbolFactory.newSymbol("FLUTUANTE",FLUTUANTE,yytext());
            }
          case 76: break;
          case 30: 
            { return symbolFactory.newSymbol("T_INT",T_INT);
            }
          case 77: break;
          case 31: 
            { return symbolFactory.newSymbol("K_NEW",K_NEW);
            }
          case 78: break;
          case 32: 
            { return symbolFactory.newSymbol("K_ELSE",K_ELSE);
            }
          case 79: break;
          case 33: 
            { return symbolFactory.newSymbol("B_TRUE",B_TRUE);
            }
          case 80: break;
          case 34: 
            { return symbolFactory.newSymbol("K_THIS",K_THIS);
            }
          case 81: break;
          case 35: 
            { return symbolFactory.newSymbol("T_VOID",T_VOID);
            }
          case 82: break;
          case 36: 
            { return symbolFactory.newSymbol("K_MAIN",K_MAIN);
            }
          case 83: break;
          case 37: 
            { return symbolFactory.newSymbol("K_CLASS",K_CLASS);
            }
          case 84: break;
          case 38: 
            { return symbolFactory.newSymbol("K_WHILE",K_WHILE);
            }
          case 85: break;
          case 39: 
            { return symbolFactory.newSymbol("B_FALSE",B_FALSE);
            }
          case 86: break;
          case 40: 
            { return symbolFactory.newSymbol("K_LENGTH",K_LENGTH);
            }
          case 87: break;
          case 41: 
            { return symbolFactory.newSymbol("K_RETURN",K_RETURN);
            }
          case 88: break;
          case 42: 
            { return symbolFactory.newSymbol("K_STATIC",K_STATIC);
            }
          case 89: break;
          case 43: 
            { return symbolFactory.newSymbol("K_PUBLIC",K_PUBLIC);
            }
          case 90: break;
          case 44: 
            { return symbolFactory.newSymbol("T_STRING",T_STRING);
            }
          case 91: break;
          case 45: 
            { return symbolFactory.newSymbol("K_EXTENDS",K_EXTENDS);
            }
          case 92: break;
          case 46: 
            { return symbolFactory.newSymbol("T_BOOLEAN",T_BOOLEAN);
            }
          case 93: break;
          case 47: 
            { return symbolFactory.newSymbol("K_PRINT",K_PRINT);
            }
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
