package analise;

//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 27 18:10:03 GMT-03:00 2015
//----------------------------------------------------

public interface sym {

	/** CUP generated class containing symbol constants. */
	/* terminals */
	public static final int K_NEW = 25;
	public static final int COLCHE_ESQ = 14;
	public static final int PONTOVIRGULA = 6;
	public static final int K_LENGTH = 27;
	public static final int B_FALSE = 42;
	public static final int K_MAIN = 26;
	public static final int OP_GT = 35;
	public static final int K_THIS = 24;
	public static final int OP_NOT = 48;
	public static final int OP_AND = 30;
	public static final int K_PRINT = 28;
	public static final int K_EXTENDS = 18;
	public static final int T_INT = 38;
	public static final int K_IF = 21;
	public static final int PARENT_ESQ = 10;
	public static final int OP_GET = 36;
	public static final int VIRGULA = 8;
	public static final int PONTO = 7;
	public static final int IDENTIFICADOR = 4;
	public static final int IGUAL = 9;
	public static final int CURLY_ESQ = 12;
	public static final int COLCHE_DIR = 15;
	public static final int K_STATIC = 19;
	public static final int K_ELSE = 22;
	public static final int A_MINUS = 44;
	public static final int OP_DIF = 32;
	public static final int EOF = 0;
	public static final int error = 1;
	public static final int OP_LT = 33;
	public static final int B_TRUE = 41;
	public static final int COMENTARIO = 5;
	public static final int OP_OR = 29;
	public static final int FLUTUANTE = 3;
	public static final int K_CLASS = 16;
	public static final int A_DIV = 46;
	public static final int A_MULT = 45;
	public static final int PARENT_DIR = 11;
	public static final int K_RETURN = 23;
	public static final int T_STRING = 40;
	public static final int OP_LET = 34;
	public static final int T_BOOLEAN = 39;
	public static final int CURLY_DIR = 13;
	public static final int INTEIRO = 2;
	public static final int A_MOD = 47;
	public static final int OP_EQ = 31;
	public static final int K_PUBLIC = 17;
	public static final int A_PLUS = 43;
	public static final int T_VOID = 37;
	public static final int K_WHILE = 20;
}




